In [27]:
import numpy as np
D = np.array([[1, 2], [3, 4]])
try:
    np.copyto(E, D)
except NameError as e:
    print("Lỗi xảy ra:", e)
E = np.array([[1, 2], [3, 5]])
np.copyto(E, D)
print("Giá trị của E sau khi sao chép từ D:")
print(E)


Giá trị của E sau khi sao chép từ D:
[[1 2]
 [3 4]]


In [28]:
import numpy as np
x = np.array([['a','b'],['c','d']])
y = 'x'
C = np.array([[x, y], [1, 2]], dtype=object)
print(C)


[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]


In [29]:
import numpy as np
print("=== Thử tạo np.matrix với mảng 3 chiều ===")
try:
    A = np.matrix([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
except ValueError as e:
    print("Lỗi khi tạo np.matrix:")
    print(e)
print("\n=== Tạo np.array với mảng 3 chiều ===")
A = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Mảng A (np.array):")
print(A)


=== Thử tạo np.matrix với mảng 3 chiều ===
Lỗi khi tạo np.matrix:
matrix must be 2-dimensional

=== Tạo np.array với mảng 3 chiều ===
Mảng A (np.array):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
from numpy import matlib
print("=== Ma trận đơn vị 5x5 ===")
G = matlib.identity(5)  
print(G)
print("\n=== Ma trận ngẫu nhiên 3x2 với phân phối chuẩn ===")
H = matlib.randn(3, 2)  
print(H)
print("\n=== Ma trận 0 kích thước 4x4 ===")
K = matlib.zeros([4, 4])  
print(K)


=== Ma trận đơn vị 5x5 ===
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

=== Ma trận ngẫu nhiên 3x2 với phân phối chuẩn ===
[[-0.11253464  1.55132031]
 [-0.16838153  0.73930345]
 [-1.04801689 -0.25310484]]

=== Ma trận 0 kích thước 4x4 ===
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
M = np.mat([[1, 2], [3, 4]])
for i in range(len(c)):
    ci = np.mat([[1, 1], [1, 0]])
    ci[0, 0] = c[i]
    if i == 0:
        M = ci
    else:
        M = M.dot(ci)
print("Ma trận M cuối cùng:")
print(M)
pi_approx = M[0, 0] / M[1, 0]
print("\nGiá trị gần đúng của số Pi:")
print(pi_approx)


Ma trận M cuối cùng:
[[165707065  80143857]
 [ 52746197  25510582]]

Giá trị gần đúng của số Pi:
3.1415926535897936


In [32]:
import numpy as np
x_data = np.array([1, 2, 3, 4, 5, 6, 7])    
y_data = np.array([3, 4, 2, 5, 6, 5, 7])   
X = np.column_stack((np.ones_like(x_data), x_data))  
Y = y_data.reshape(-1, 1) 
XT = X.T
A1 = np.linalg.inv(XT @ X) @ XT
A2 = A1 @ Y
print("Hệ số hồi quy (A2):")
print(A2)
a0, a1 = A2[0, 0], A2[1, 0]
print(f"\nPhương trình hồi quy: y = {a0:.4f} + {a1:.4f} * x")
y_pred = X @ A2
squared_errors = (Y - y_pred) ** 2
total_error = np.sum(squared_errors)
print(f"\nTổng bình phương sai số: {total_error:.4f}")


Hệ số hồi quy (A2):
[[2.        ]
 [0.64285714]]

Phương trình hồi quy: y = 2.0000 + 0.6429 * x

Tổng bình phương sai số: 6.1429


In [33]:
import numpy as np
from numpy import linalg
def bpcuctieu(a): 
    b = []   
    o1 = []  
    for i in range(len(a)):
        o1.append(1.0)        
        b.append((i + 1) * 1.0) 
    x = np.array([o1, b]).T   
    u = np.dot(x.T, x)         
    y = np.array(a).reshape(-1, 1) 
    u_1 = linalg.inv(u)        
    v = np.dot(u_1, x.T)       
    A = np.dot(v, y)           

    return A  


In [34]:
dulieu = [10.0, 8.0, 7.0, 5.0, 2.0]   
A = bpcuctieu(dulieu)

a0 = A[0, 0]
a1 = A[1, 0]

print(f"Phương trình tuyến tính là: y = {a0:.1f} + ({a1:.1f})x")


Phương trình tuyến tính là: y = 12.1 + (-1.9)x
