In [143]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

tich_inner = np.inner(a, b)
tich_dot = np.dot(a, b)

print("Tích vô hướng (inner):", tich_inner)
print("Tích vô hướng (dot):", tich_dot)

print("Hai kết quả có giống nhau không?", np.array_equal(tich_inner, tich_dot))

Tích vô hướng (inner): 32
Tích vô hướng (dot): 32
Hai kết quả có giống nhau không? True


In [144]:
a = np.array([1, 2, -3])
norm_2 = np.linalg.norm(a) 
print(norm_2)
norm_1 = np.linalg.norm(a, 1)
print(norm_1)

3.7416573867739413
6.0


In [145]:
import math

def chuan(vector, p):
    return (sum(abs(x) ** p for x in vector)) ** (1/p)

a = np.array([1, 2, -3])

result_1 = chuan(a, 1)  
result_2 = np.linalg.norm(a, 1)  
result_3 = chuan(a, 2)  
result_4 = np.linalg.norm(a, 2)  
result_5 = chuan(a, 3) 
result_6 = np.linalg.norm(a, 3) 
result_7 = chuan(a, 1000)  
result_8 = np.linalg.norm(a, 1000)  

print(result_1)
print(result_2)
print(result_3)
print(result_4)
print(result_5)
print(result_6)
print(result_7)
print(result_8)

6.0
6.0
3.7416573867739413
3.7416573867739413
3.3019272488946263
3.3019272488946263
nan
inf


C:\Users\Admin\AppData\Local\Temp\ipykernel_9772\1951074243.py:4: RuntimeWarning: invalid value encountered in power
  return (sum(abs(x) ** p for x in vector)) ** (1/p)


In [146]:
from scipy import linalg

a = np.array([1, 2, -3])

result_1 = linalg.norm(a) 
result_2 = linalg.norm(a, 100)  
result_3 = linalg.norm(a, 1000) 

print(result_1)
print(result_2)
print(result_3)

3.7416573867739413
3.0
inf


In [147]:

m = 10
v1 = np.array([5, -4, 3])
v2 = np.array([4, 3, -2])
v3 = np.array([-4, -3, -1])
v4 = np.array([-9, 8, 6])
mi = np.array([2, 5, 2, 1])
M = np.array([v1, v2, v3, v4])

MT = M.transpose()
print(MT)

v = (1.0 / m) * MT.dot(mi)
print(v)

[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]
[1.3 0.9 0. ]


In [148]:

# Khai báo ma trận A
A = np.array([[0.998, 0.136],
              [0.002, 0.864]])

# Khai báo vector v0
v0 = np.array([0.95, 0.05])

# Tính A^100
A_power_100 = np.linalg.matrix_power(A, 100)

# Tính vector x100 và y100
result = A_power_100.dot(v0)
x100 = result[0]
y100 = result[1]

print("x100 (tỷ lệ thất nghiệp):", x100)
print("y100 (tỷ lệ có việc làm):", y100)

x100 (tỷ lệ thất nghiệp): 0.9855072337572737
y100 (tỷ lệ có việc làm): 0.01449276624272995


In [149]:
import sympy as sym

x, y = sym.symbols('x y')
xy = sym.Matrix([x, y])  

A = sym.Matrix([[1, -68], [1, 1]])
v = sym.Matrix([0, 1])

nghiem = sym.solve([A * xy - v])

print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [150]:

A = np.array([[1, 6],
              [5, 2]])
u = np.array([[6],
              [-5]])
Au = A @ u        
right = -4 * u     

print("Au =\n", Au)
print("-4u =\n", right)
print("Kiểm tra Au == -4u:", np.allclose(Au, right))


Au =
 [[-24]
 [ 20]]
-4u =
 [[-24]
 [ 20]]
Kiểm tra Au == -4u: True


In [151]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2) 
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I - A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])
print(sympy.pretty(nghiem))


[-7.000, 3.000]
[-7, 3]


In [152]:
from numpy import linalg as LA

A = np.array([[2, 3],
              [3, -6]])

D = np.array([[-7, 0],
              [0, 3]])

P = np.array([[-1/3, 3],
              [1,    1]])

P1 = LA.inv(P)
print("P^(-1) =")
print(P1)
print()

print("A.dot(P) =")
print(A.dot(P))
print()

print("P.dot(D) =")
print(P.dot(D))
print()

A_1000 = P @ (D ** 1000) @ P1
print("A^1000 =")
print(A_1000)
print()

print("D^2 =")
print(D ** 2)


P^(-1) =
[[-0.3  0.9]
 [ 0.3  0.1]]

A.dot(P) =
[[ 2.33333333  9.        ]
 [-7.          3.        ]]

P.dot(D) =
[[ 2.33333333  9.        ]
 [-7.          3.        ]]

A^1000 =
[[-6.25396533e+08 -3.52488701e+08]
 [-3.52488701e+08  3.14573335e+08]]

D^2 =
[[49  0]
 [ 0  9]]


In [153]:
a = np.array([1,2,3])
mag = np.sqrt(a.dot(a))
print (mag) 

3.7416573867739413


In [154]:
mag = np.sqrt(a @ a )
print(mag)

3.7416573867739413


In [155]:
mag = np.sqrt(np.inner(a,a))
print(mag)

3.7416573867739413


In [156]:
mag = lambda x : math.sqrt(sum(i** 2 for i in x))
print(mag(a))

3.7416573867739413


In [157]:
from numpy import linalg as LA

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

distance = LA.norm(u - v)
print("||u - v|| =", distance)

cos_theta = np.dot(u, v) / (LA.norm(u) * LA.norm(v))
theta = np.arccos(cos_theta)
print("Góc giữa u và v (radian) =", theta)

p = (np.dot(u, v) / np.dot(v, v)) * v
print("Phép chiếu p =", p)

||u - v|| = 5.196152422706632
Góc giữa u và v (radian) = 0.2257261285527342
Phép chiếu p = [1.66233766 2.07792208 2.49350649]
